//@version=5

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RezzaHmt

//...VWEMA...
strategy(title="Volume Weight Exponential Bollinger Bands Momentum Strategy", shorttitle="VWEMABB Momentum Strategy", overlay=true,initial_capital = 10000)
src = input(hl2, title="Source")

EntryPeriod = input.int(9, minval=2, maxval=20, title="EntryPeriod")
useEntryPeriod = input.bool(0,"Use Entry Period")

AccuracyTest = input.bool(0,"Accuracy Test")
WithLTDMA = input.bool(0,"With Long Term MA")

EVMAAlpha = input.float(0.9,minval = 0.1,maxval = 1,title = "EVMA Alpha")


DailyShortTermPeriod = input.int(20, minval=1, maxval=2000, title="DailyShortTermPeriod")
DailyLongTermPeriod = input.int(200, minval=1, maxval=2000, title="DailyPeriod")
WeeklyPeriod = input.int(100, minval=1, maxval=2000, title="WeeklyPeriod")

startDate = input.int(title="Start Date", defval=1, minval=1, maxval=31)
startMonth = input.int(title="Start Month", defval=1, minval=1, maxval=12)
startYear = input.int(title="Start Year", defval=2018, minval=1800, maxval=2100)

afterStartDate = (time >= timestamp(syminfo.timezone, startYear, startMonth, startDate, 0, 0))

StopPercentage = input.float(title="Stop Percentage", defval=0.9, minval=0, maxval=2)


f_evwma(_src, alpha, _len)=>
    _alpha = alpha//2 / (_len + 1)
    _evwma = 0.0
    _cumVol = 0.0
    _cumVal = 0.0
    _x = _len
    while _x > 0
        _cumVol := _cumVol + volume[_x]
        _cumVal := _cumVal + (_src[_x]*volume[_x])
        _x:=_x-1
    _evwma := (_cumVal/_cumVol) * _alpha + nz(_evwma[1]) * (1 - _alpha)
    _evwma



//set SUM function for stdev
isZero(val, eps) => math.abs(val) <= eps

SUM(fst, snd) =>
    EPS = 1e-10
    res = fst + snd
    if isZero(res, EPS)
        res := 0
    else
        if not isZero(res, 1e-4)
            res := res
        else
            15

//stdev function
pine_stdev(src, basis, length) =>
    avg = basis
    sumOfSquareDeviations = 0.0
    for i = 0 to length - 1
        sum = SUM(src[i], -avg)
        sumOfSquareDeviations := sumOfSquareDeviations + sum * sum
    stdev = math.sqrt(sumOfSquareDeviations / length)


//get 52 week high
LHigh(src,length) =>
    thisHigh = 0.0
    for i = 0 to length - 1
        if high[i] > thisHigh
            thisHigh:= high[i]
    thisHigh

LLow(src,length) =>
    thisLow = low
    for i = 0 to length - 1
        if low[i] < thisLow
            thisLow:= low[i]
    thisLow

Week52High = LHigh(src,200)
Week52Low = LLow(src,200)

plot(Week52High,title="52WeekHigh", color=color.aqua, linewidth=1)
plot(Week52Low,title="52WeekLow", color=color.red, linewidth=1)

//------------------------------------------------------------------------------------------
//Daily Short Term Time Frame

DoubleExponential = input.bool(0,title="Double Exponential?")

DSTEvma1 = f_evwma(src, EVMAAlpha, DailyShortTermPeriod)
DSTEvma2 = f_evwma(src, EVMAAlpha, DailyShortTermPeriod*0.75)
DSTEvma3 = f_evwma(src, EVMAAlpha, DailyShortTermPeriod*0.5)
DSTEvma4 = f_evwma(src, EVMAAlpha, DailyShortTermPeriod*0.25)

DSTEVMA = (DSTEvma1+DSTEvma2+DSTEvma3+DSTEvma4) / 4

DSTstd1 = 2 * ta.stdev(src,DailyShortTermPeriod)
DSTstd2 = 2 * ta.stdev(src,int(DailyShortTermPeriod*0.75))
DSTstd3 = 2 * ta.stdev(src,int(DailyShortTermPeriod*0.5))
DSTstd4= 2 * ta.stdev(src,int(DailyShortTermPeriod*0.25))

DSTSTD = (DSTstd1+DSTstd2+DSTstd3+DSTstd4) / 4

//Now create the momentum equivalent
DSTHigh1 = LHigh(src,DailyLongTermPeriod)
DSTHigh2 = LHigh(src,int(DailyShortTermPeriod*0.75))
DSTHigh3 = LHigh(src,int(DailyShortTermPeriod*0.5))
DSTHigh4 = LHigh(src,int(DailyShortTermPeriod*0.25))

DSTHigh = (DSTHigh1+DSTHigh2+DSTHigh3+DSTHigh4) / 4



DSTLow1 = LLow(src,DailyLongTermPeriod)
DSTLow2 = LLow(src,int(DailyShortTermPeriod*0.75))
DSTLow3 = LLow(src,int(DailyShortTermPeriod*0.5))
DSTLow4 = LLow(src,int(DailyShortTermPeriod*0.25))

DSTLow = (DSTLow1+DSTLow2+DSTLow3+DSTLow4) / 4


if (DoubleExponential==1)
    DSTEvma5 = f_evwma(src, EVMAAlpha, int(DailyShortTermPeriod*0.25))
    DSTEvma6 = f_evwma(src, EVMAAlpha, int(DailyShortTermPeriod*0.125))
    DSTEvma7 = f_evwma(src, EVMAAlpha, int(DailyShortTermPeriod*0.0625))
    DSTEvma8 = f_evwma(src, EVMAAlpha, int(DailyShortTermPeriod*0.03125))

    DSTEVMA := (DSTEvma1+DSTEvma2+DSTEvma3+DSTEvma4+DSTEvma5+DSTEvma6+DSTEvma7+DSTEvma8) / 8


    DSTstd5 = 2 * ta.stdev(src,int(DailyShortTermPeriod*0.25))
    DSTstd6 = 2 * ta.stdev(src,int(DailyShortTermPeriod*0.125))
    DSTstd7 = 2 * ta.stdev(src,int(DailyShortTermPeriod*0.0625))
    DSTstd8 = 2 * ta.stdev(src,int(DailyShortTermPeriod*0.03125))

    DSTSTD := (DSTstd1+DSTstd2+DSTstd3+DSTstd4+DSTstd5+DSTstd6+DSTstd7+DSTstd8) / 8

    DSTHigh5 = LHigh(src,int(DailyLongTermPeriod*0.25))
    DSTHigh6 = LHigh(src,int(DailyShortTermPeriod*0.125))
    DSTHigh7 = LHigh(src,int(DailyShortTermPeriod*0.0625))
    DSTHigh8 = LHigh(src,int(DailyShortTermPeriod*0.03125))

    DSTHigh := (DSTHigh1+DSTHigh2+DSTHigh3+DSTHigh4+DSTHigh5+DSTHigh6+DSTHigh7+DSTHigh8) / 8

    DSTLow5 = LLow(src,int(DailyLongTermPeriod*0.25))
    DSTLow6 = LLow(src,int(DailyShortTermPeriod*0.125))
    DSTLow7 = LLow(src,int(DailyShortTermPeriod*0.0625))
    DSTLow8 = LLow(src,int(DailyShortTermPeriod*0.03125))

    DSTLow := (DSTLow1+DSTLow2+DSTLow3+DSTLow4+DSTLow5+DSTLow6+DSTLow7+DSTLow8) / 8



DSTUPPER = DSTEVMA + DSTSTD
DSTLOWER = DSTEVMA - DSTSTD

plot(DSTHigh,title="DSTHigh",color=color.lime)
plot(DSTLow,title="DSTLow",color=color.maroon)

//------------------------------------------------------------------------------------------
//Entry Period

EntryEVMA = f_evwma(src, EVMAAlpha, EntryPeriod)
plot(EntryEVMA, title="EntryEVMA", color=color.new(#62ff3b, 0), linewidth=1)


plot(DSTEVMA, title="VWEMA", color=color.new(color.yellow, 0), linewidth=1)
plot(series=DSTUPPER, color=color.new(color.red, 0), linewidth=1)
plot(series=DSTLOWER, color=color.new(color.blue, 0), linewidth=1)

//------------------------------------------------------------------------------------------
// Long Term Daily

LTDEvma1 = f_evwma(src, EVMAAlpha, DailyLongTermPeriod)
LTDEvma2 = f_evwma(src, EVMAAlpha, DailyLongTermPeriod*0.75)
LTDEvma3 = f_evwma(src, EVMAAlpha, DailyLongTermPeriod*0.5)
LTDEvma4 = f_evwma(src, EVMAAlpha, DailyLongTermPeriod*0.25)

LTDEVMA = (LTDEvma1+LTDEvma2+LTDEvma3+LTDEvma4) / 4

LTDstd1 = 2 * ta.stdev(src,DailyLongTermPeriod) //pine_stdev(src,LTDEvma1,DailyLongTermPeriod)
LTDstd2 = 2 * ta.stdev(src,int(DailyLongTermPeriod*0.75)) //pine_stdev(src,LTDEvma2,DailyLongTermPeriod*0.75)
LTDstd3 = 2 * ta.stdev(src,int(DailyLongTermPeriod*0.5))
LTDstd4= 2 * ta.stdev(src,int(DailyLongTermPeriod*0.25))

LTDSTD = (LTDstd1+LTDstd2+LTDstd3+LTDstd4) / 4

LTDUPPER = LTDEVMA + LTDSTD
LTDLOWER = LTDEVMA - LTDSTD

//------------------------------------------------

//Short Term Weekly
WSTEvma1 = f_evwma(src, EVMAAlpha, WeeklyPeriod)
WSTEvma2 = f_evwma(src, EVMAAlpha, WeeklyPeriod*0.75)
WSTEvma3 = f_evwma(src, EVMAAlpha, WeeklyPeriod*0.5)
WSTEvma4 = f_evwma(src, EVMAAlpha, WeeklyPeriod*0.25)

WSTEVMA = (WSTEvma1+WSTEvma2+WSTEvma3+WSTEvma4) / 4

WSTstd1 = 2 * ta.stdev(src,WeeklyPeriod)
WSTstd2 = 2 * ta.stdev(src,int(WeeklyPeriod*0.75))
WSTstd3 = 2 * ta.stdev(src,int(WeeklyPeriod*0.5))
WSTstd4= 2 * ta.stdev(src,int(WeeklyPeriod*0.25))

WSTSTD = (WSTstd1+WSTstd2+WSTstd3+WSTstd4) / 4

WSTUPPER = WSTEVMA + WSTSTD
WSTLOWER = WSTEVMA - WSTSTD
//plot(WSTEVMA, title="VWEMA", color=color.new(color.orange, 75), linewidth=2)
//plot(series=WSTUPPER, color=color.new(color.green, 50), linewidth=1, style=plot.style_cross)
//plot(series=WSTLOWER, color=color.new(color.purple, 50), linewidth=1, style=plot.style_cross)

//------------------------------------------------------------------------------------------
//Mold Daily Long Term and Weekly into similar weighting
//======================================================
//Molded because DailyLT is longer than short term weekly,
//so joining seems appropriate given other traders will be looking at each.

LTEVMA = (WSTEVMA+LTDEVMA)/2
LTUPPER = (WSTUPPER+LTDUPPER)/2
LTLOWER = (WSTLOWER+LTDLOWER)/2
//plot(LTEVMA, title="VWEMA", color=color.new(color.orange, 75), linewidth=2)
//plot(series=LTUPPER, color=color.new(color.green, 50), linewidth=1, style=plot.style_cross)
//plot(series=LTLOWER, color=color.new(color.purple, 50), linewidth=1, style=plot.style_cross)
//------------------------------------------------------------------------------------------

//------------------------------------------------------------------------------------------
//Longer Term
LGTEVMA = f_evwma(src, 0.9, DailyLongTermPeriod)
LGTSTD = 2 * ta.stdev(src,DailyLongTermPeriod)
LGTUPPER = LGTEVMA+LGTSTD
LGTLOWER = LGTEVMA-LGTSTD

plot(series=LGTUPPER, color=color.new(color.red, 50), linewidth=1, style=plot.style_circles)
plot(series=LGTLOWER, color=color.new(color.red, 50), linewidth=1, style=plot.style_circles)
plot(series=LGTEVMA, color=color.new(color.red, 70), linewidth=2)
//------------------------------------------------------------------------------------------

//TTM Squeeze

std20by2 = ta.stdev(hl2,20,true)*2
atr20by15 = ta.atr(20)*1.5
momOsc = ta.mom(src,20)

bband(length, alph, mult) =>
    ta.sma(close, length) + mult * ta.stdev(close, length)

keltner(length, alph, mult) =>
    ta.ema(close, length) + mult * ta.ema(ta.atr(length), length)


// bband(length, alph, mult) =>
//     f_evwma(hl2, alph, length) + mult * ta.stdev(hl2, length)

// keltner(length, alph, mult) =>
//     f_evwma(hl2, alph, length) + mult * ta.ema(ta.atr(length), length)

e1 = (ta.highest(close,20) + ta.lowest(close, 20)) / 2 + ta.sma(close, 20)
osc = ta.linreg(close - e1 / 2, 20, 0)
tbband = bband(20, EVMAAlpha, 2)
tkc = keltner(20, EVMAAlpha, 1)
diff = tbband - tkc
osc_color = osc[1] < osc[0] ? osc[0] >= 0 ? #00ffff : #cc00cc : osc[0] >= 0 ? #009b9b : #ff9bff
//mid_color = diff >= 0 ? color.green : color.red


TTMSHigh = DSTEVMA
TTMSLOW = DSTEVMA

if(std20by2 < atr20by15)
    TTMSHigh:= TTMSHigh+std20by2
    TTMSLOW:= TTMSLOW-std20by2

p1 = plot(TTMSHigh, color = color.new(color.orange,100))
p2 = plot(TTMSLOW, color = color.new(color.orange,100))

thiscolor = 0
momColor = color.new(color.yellow,70)

if std20by2 <= atr20by15 // diff >= 0
    thiscolor := 1

if osc[0] >= 1 or osc[0] <= -1
    momColor := osc[1] < osc[0] ? osc[0] >= 0 ? color.new(#00ffff,80) : color.new(#cc00cc,80) : osc[0] >= 0 ? color.new(#009b9b,80) : color.new(#ff9bff,80)
    //momColor := osc[1] < osc[0] ? osc[0] >= 0 ? color.new(color.lime,70) : color.new(color.maroon,70) : osc[0] >= 0 ? color.new(color.green,70) : color.new(color.red,70)

fill(p1,p2, color = thiscolor ? momColor : na)




//------------------------------------------------------------------------------------------


//Are we taking this strategy short
Short = input.int(0, title="LongShort")

//Strategy
equityType = input.bool(1,title="All In?")

account = strategy.equity

if (equityType == 0)
    account:= strategy.initial_capital

tier = math.round((strategy.position_size*close/account),3)

lastclosedtrade = strategy.closedtrades.exit_id(strategy.closedtrades - 1)



//strategy Daily short term, Weekly short term, mid term (sW+ld/2), long term d200,
StrategyType = input.int(1, minval=1, maxval=4, title="StrategyType")



upper = DSTUPPER
middle = DSTEVMA
lower = DSTLOWER

if (StrategyType==1)
    upper := DSTUPPER
    middle := DSTEVMA
    lower := DSTLOWER
else if (StrategyType==2)
    upper := WSTUPPER
    middle := WSTEVMA
    lower := WSTLOWER
else if (StrategyType==3)
    upper := LTUPPER
    middle := LTEVMA
    lower := LTLOWER
else if (StrategyType==4)
    upper := LGTUPPER
    middle := LGTEVMA
    lower := LGTLOWER

momentum = input.bool(0,title="momentum")

squeeze = input.bool(0,title="squeeze")

//plot squeeze against lower
plot(lower,"bb<atr1",color= diff<0 ? color.red : na, style=plot.style_circles)


TouchedDSTHigh = 0
for iDSTH = 0 to 9
    if high[iDSTH] >= DSTHigh
        TouchedDSTHigh:=1

TouchedDSTLow = 0
for iDSTL = 0 to 9
    if low[iDSTL] <= DSTLow
        TouchedDSTLow:=1



if (momentum == 0)

    //if we are set to going long
    if (Short == 0)
        if (afterStartDate and tier == 0) //and lastclosedtradebar < bar_index-2)
            if(useEntryPeriod == 0)
                if (WithLTDMA == 0)
                    if (low < lower) // and (volume[1] > VolumeAverage*1.25))
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))
                else
                    if (low <= lower and DSTEVMA > LTDEVMA) // and (volume[1] > VolumeAverage*1.25))
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))
            else if (useEntryPeriod == 1)
                if (WithLTDMA == 0)
                    if ((close[1] <= lower[1] or close[2] <= lower[2] or close[3] <= lower[3]) and close >= EntryEVMA and close >= open and close <= DSTEVMA[1] and EntryEVMA < DSTEVMA)
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=EntryEVMA, comment="tier: "+str.tostring(lastclosedtrade))
                else
                    if ((close[1] <= lower[1] or close[2] <= lower[2] or close[3] <= lower[3]) and close >= EntryEVMA and close >= open and close <= DSTEVMA[1] and EntryEVMA < DSTEVMA and DSTEVMA > LTDEVMA)
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=EntryEVMA, comment="tier: "+str.tostring(lastclosedtrade))

        //ExitPause = (strategy.opentrades.entry_bar_index(0)+3) < bar_index

        if strategy.opentrades > 0
            if (AccuracyTest == 0)
                //if(tier >= 0.9)
                if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    if(high >= middle)
                        //tier1 = label.new(bar_index, low, text="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", qty=(strategy.position_size/2), comment="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("1","Buy", qty=(strategy.position_size/2), profit = 0.1, loss = 0.1, comment="tier: 1") //+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                    if(low <= strategy.opentrades.entry_price(0)*StopPercentage) //and ExitPause == 1)
                        //tier1out = label.new(bar_index, low, text="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", comment="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Buy", profit = 0.1, loss = 0.1, comment="tier: 1 close")
                        if (low > lower)
                            strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))
            else
                if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    if(high >= middle)
                        strategy.exit("0","Buy", profit = 0.1, loss = 0.1, comment="tier: 1 close won")
                    if(low <= strategy.opentrades.entry_price(0)*StopPercentage)
                        strategy.exit("0","Buy", profit = 0.1, loss = 0.1, comment="tier: 1 close loss")

        if strategy.closedtrades > 0
            if (AccuracyTest == 0)
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "1")
                    if(high >= upper)

                        strategy.exit("2","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size/2) , comment="tier: 2")

                    if(low <= strategy.opentrades.entry_price(0))

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 2 close")

                    if(low <= lower) //open up new trade

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 2 close")
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))


            if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "2")
                if (AccuracyTest == 0)
                    //if it is coming down, but not quite out
                    if(low <= middle)

                        strategy.exit("3","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size/2), comment="tier: 3")

                    if(low <= strategy.opentrades.entry_price(0))

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 3 close")

                    if(low <= lower )

                        strategy.exit("0","Buy",  profit = 0.1, loss=0.1, comment="tier: 3 close")
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))

            //if(tier >= 0.0001 and tier <= 0.25)
            if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "3")
                if (AccuracyTest == 0)
                    if(low <= strategy.opentrades.entry_price(0))

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 4 close")

                    if(low <= lower)
                        //tier4out = label.new(bar_index, low, text="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy",comment="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 4 close")//"tier3closeout: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))

    //Short strategy
    if (Short == 1)
        //Update Stop Percentage on Short Positions
        StopPercentage := 2-StopPercentage

        if (afterStartDate and tier == 0) //and lastclosedtradebar < bar_index-2)
            if(useEntryPeriod == 0)
                if (WithLTDMA == 0)
                    if (high >= upper) // and (volume[1] > VolumeAverage*1.25))
                        strategy.entry("Sell", strategy.short, qty=math.abs(math.round((account/(close*0.9)))), limit=upper, comment="tier: "+str.tostring(lastclosedtrade)) //+", Vol:"+str.tostring(volume[0])+", VA: "+str.tostring(VolumeAverage))
                else
                    if (high >= upper) // and (volume[1] > VolumeAverage*1.25))
                        strategy.entry("Sell", strategy.short, qty=math.abs(math.round((account/(close*0.9)))), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))
            else
                if (WithLTDMA == 0)
                    if ((close[1] >= upper[1] or close[2] >= upper[2] or close[3] >= upper[3]) and close <= EntryEVMA and close <= open and close >= DSTEVMA[1] and EntryEVMA > DSTEVMA)
                        strategy.entry("Sell", strategy.short, qty=math.abs(math.round((account/(close*0.9)))), limit=upper, comment="tier: "+str.tostring(lastclosedtrade)) //+", Vol:"+str.tostring(volume[0])+", VA: "+str.tostring(VolumeAverage))
                else
                    if ((close[1] >= upper[1] or close[2] >= upper[2] or close[3] >= upper[3]) and close <= EntryEVMA and close <= open and close >= DSTEVMA[1] and EntryEVMA > DSTEVMA and DSTEVMA < LTDEVMA)
                        strategy.entry("Sell", strategy.short, qty=math.abs(math.round((account/(close*0.9)))), limit=upper, comment="tier: "+str.tostring(lastclosedtrade)) //+", Vol:"+str.tostring(volume[0])+", VA: "+str.tostring(VolumeAverage))
                //and (volume[bar_index]) >= VolumeAverage
                //bought = label.new(bar_index, low, text="tier: "+str.tostring(math.round((strategy.position_size/account)))+", Vol:"+str.tostring(volume[0])+", VA: "+str.tostring(VolumeAverage), color=color.blue )
                //label.new(bar_index, high, str.tostring(math.round((strategy.position_size/account))))
                //plot(label1)
                //plotchar(data, char='❄')

        ExitPause = (strategy.opentrades.entry_bar_index(0)+3) < bar_index

        if strategy.opentrades > 0
            if (AccuracyTest == 0)
                if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    if(high <= middle)
                        //tier1 = label.new(bar_index, low, text="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", qty=(strategy.position_size/2), comment="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("1","Sell", qty=(math.abs(strategy.position_size)/2), profit = 0.1, loss = 0.1, comment="tier: 1") //+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                    if(high >= strategy.opentrades.entry_price(0)*StopPercentage) //and ExitPause == 1)
                        //tier1out = label.new(bar_index, low, text="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", comment="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Sell", profit = 0.1, loss = 0.1, qty=math.abs(strategy.position_size), comment="tier: 1 close")//"tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                //if(tier >= 0.4 and tier <=0.9)
            else
                if(high <= middle)
                    strategy.exit("0","Sell", profit = 0.1, loss = 0.1, qty=math.abs(strategy.position_size), comment="tier: 1 close win")
                if(high >= strategy.opentrades.entry_price(0)*StopPercentage)
                    strategy.exit("0","Sell", profit = 0.1, loss = 0.1, qty=math.abs(strategy.position_size), comment="tier: 1 close loss")


        if strategy.closedtrades > 0
            if (AccuracyTest == 0)
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "1")
                    if(low <= lower)

                        strategy.exit("2","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)/2) , comment="tier: 2")

                    if(high >= upper or high >= strategy.opentrades.entry_price(0)) //open up new trade

                        strategy.exit("0","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)), comment="tier: 2 close")
                        if high >= upper
                            strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))


                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "2")

                    //if it is coming down, but not quite out
                    if(high >= middle)

                        strategy.exit("3","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)/2), comment="tier: 3")

                    if(high >= strategy.opentrades.entry_price(0) and high >= upper)

                        strategy.exit("0","Sell",  profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)), comment="tier: 3 close")
                        if high >= upper
                            strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))

                //if(tier >= 0.0001 and tier <= 0.25)
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "3")

                    if(high >= upper or high >= strategy.opentrades.entry_price(0))
                        //tier4out = label.new(bar_index, low, text="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy",comment="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)), comment="tier: 4 close")

                        if(high >= upper)
                            strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))

    if (Short == 2)

        if (afterStartDate and tier == 0) //and lastclosedtradebar < bar_index-2)
            if (high >= upper) // and (volume[1] > VolumeAverage*1.25))
                strategy.entry("Sell", strategy.short, qty=math.abs(math.round((account/(close*0.9)))), limit=upper, comment="tier: "+str.tostring(lastclosedtrade)) //+", Vol:"+str.tostring(volume[0])+", VA: "+str.tostring(VolumeAverage))
            if (low <= lower) // and (volume[1] > VolumeAverage*1.25))
                strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))

        ExitPause = (strategy.opentrades.entry_bar_index(0)+3) < bar_index


        if strategy.opentrades.entry_id(strategy.opentrades - 1) == "Sell"

            //update StopPercentage on Short Positions
            StopPercentage := 2-StopPercentage

            if strategy.opentrades > 0
                //if(tier >= 0.9)
                if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    if(high <= middle)
                        //tier1 = label.new(bar_index, low, text="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", qty=(strategy.position_size/2), comment="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("1","Sell", qty=(math.abs(strategy.position_size)/2), profit = 0.1, loss = 0.1, comment="tier: 1") //+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                    if(high >= strategy.opentrades.entry_price(0)*StopPercentage) //and ExitPause == 1)
                        //tier1out = label.new(bar_index, low, text="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", comment="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Sell", profit = 0.1, loss = 0.1, qty=math.abs(strategy.position_size), comment="tier: 1 close")//"tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                //if(tier >= 0.4 and tier <=0.9)

            if strategy.closedtrades > 0
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "1")
                    if(low <= lower)

                        strategy.exit("2","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)/2) , comment="tier: 2")

                    if(high >= upper or high >= strategy.opentrades.entry_price(0)) //open up new trade

                        strategy.exit("0","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)), comment="tier: 2 close")
                        if high >= upper
                            strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))


                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "2")

                    //if it is coming down, but not quite out
                    if(high >= middle)

                        strategy.exit("3","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)/2), comment="tier: 3")

                    if(high >= strategy.opentrades.entry_price(0) and high >= upper)

                        strategy.exit("0","Sell",  profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)), comment="tier: 3 close")
                        if high >= upper
                            strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))

                //if(tier >= 0.0001 and tier <= 0.25)
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "3")

                    if(high >= upper or high >= strategy.opentrades.entry_price(0))
                        //tier4out = label.new(bar_index, low, text="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy",comment="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Sell", profit = 0.1, loss=0.1, qty=(math.abs(strategy.position_size)), comment="tier: 4 close")

                        if(high >= upper)
                            strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=upper, comment="tier: "+str.tostring(lastclosedtrade))

        if strategy.opentrades.entry_id(strategy.opentrades - 1) == "Buy"

            if strategy.opentrades > 0
                //if(tier >= 0.9)
                if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    if(high >= middle)
                        //tier1 = label.new(bar_index, low, text="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", qty=(strategy.position_size/2), comment="tier1: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("1","Buy", qty=(strategy.position_size/2), profit = 0.1, loss = 0.1, comment="tier: 1") //+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                    if(low <= strategy.opentrades.entry_price(0)*StopPercentage) //and ExitPause == 1)
                        //tier1out = label.new(bar_index, low, text="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy", comment="tier1out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Buy", profit = 0.1, loss = 0.1, comment="tier: 1 close")
                        if (low > lower)
                            strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))

            if strategy.closedtrades > 0
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "1")
                    if(high >= upper)

                        strategy.exit("2","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size/2) , comment="tier: 2")

                    if(low <= strategy.opentrades.entry_price(0))

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 2 close")

                    if(low <= lower) //open up new trade

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 2 close")
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))


                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "2")

                    //if it is coming down, but not quite out
                    if(low <= middle)

                        strategy.exit("3","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size/2), comment="tier: 3")

                    if(low <= strategy.opentrades.entry_price(0))

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 3 close")

                    if(low <= lower )

                        strategy.exit("0","Buy",  profit = 0.1, loss=0.1, comment="tier: 3 close")
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))

                //if(tier >= 0.0001 and tier <= 0.25)
                if(strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "3")
                    if(low <= strategy.opentrades.entry_price(0))

                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 4 close")

                    if(low <= lower)
                        //tier4out = label.new(bar_index, low, text="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)), color=color.green )
                        //strategy.close("Buy",comment="tier4out: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 4 close")//"tier3closeout: "+str.tostring(tier)+" oPrice:"+str.tostring(strategy.opentrades.entry_price(0)))
                        strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=lower, comment="tier: "+str.tostring(lastclosedtrade))

momentumLargePullback = input.bool(0,"momentumLargePullback")

//if momentum is switched on, we want a completely different strategy
if (momentum == 1)

    exit = DSTEVMA
    if useEntryPeriod == 1
        exit:= EntryEVMA

    if(StrategyType == 1)

        if Short == 0
            //if we are set to going long
            if strategy.opentrades == 0 and afterStartDate
                if momentumLargePullback == 0
                    if squeeze == 1
                        if(TouchedDSTHigh == 1 and low < DSTEVMA and std20by2 < atr20by15)
                            strategy.entry("Buy", strategy.long, qty=math.round((account/close)/2), limit=low, comment="tier: "+str.tostring(lastclosedtrade))
                    else
                        if(TouchedDSTHigh == 1 and low < DSTEVMA)
                            strategy.entry("Buy", strategy.long, qty=math.round((account/close)/2), limit=low, comment="tier: "+str.tostring(lastclosedtrade))
                else
                    if squeeze == 1
                        if(TouchedDSTHigh == 1 and low < lower and std20by2 < atr20by15)
                            strategy.entry("Buy", strategy.long, qty=math.round((account/close)/2), limit=low, comment="tier: "+str.tostring(lastclosedtrade))
                    else
                        if(TouchedDSTHigh == 1 and low < lower)
                            strategy.entry("Buy", strategy.long, qty=math.round((account/close)/2), limit=low, comment="tier: "+str.tostring(lastclosedtrade))


            if strategy.opentrades.entry_id(strategy.opentrades - 1) == "Buy"
                if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    //if AccuracyTest == 1
                    if strategy.opentrades > 0
                        if high >= upper
                            strategy.exit("0","Buy", profit = 0.1, loss=0.1, limit=low, qty=(strategy.position_size), comment="close tier: 1")
                        if (low <= strategy.opentrades.entry_price(0)*StopPercentage) //  and (strategy.position_size*close) < (strategy.equity/2))
                            strategy.exit("0","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size), comment="closed out: 1")
                    // else
                    //     if strategy.opentrades > 0
                    //         //Now we want to create tiers
                    //         if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "0" or strategy.closedtrades == 0)
                    //             if high >= upper
                    //                 strategy.exit("1","Buy", profit = 0.1, loss=0.1, limit=low, qty=math.round(strategy.position_size/2), comment="close tier: 1")
                    //             if (low <= strategy.opentrades.entry_price(0)*StopPercentage) //  and (strategy.position_size*close) < (strategy.equity/2))
                    //                 strategy.exit("1","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size), comment="closed out: 1")
                    //         //if past tier 1
                    //         if (strategy.closedtrades.exit_id(strategy.closedtrades - 1) == "1" and strategy.position_size > 0)
                    //             if low <= lower
                    //                 strategy.exit("2","Buy", profit = 0.1, loss=0.1, limit=low, qty=(strategy.position_size), comment="close tier: 2")
                    //             if (low <= strategy.opentrades.entry_price(0)) //  and (strategy.position_size*close) < (strategy.equity/2))
                    //                 strategy.exit("2","Buy", profit = 0.1, loss=0.1, qty=(strategy.position_size), comment="closed out: 2")

    //momentum shift
    if(StrategyType == 2)
        if strategy.opentrades == 0 and afterStartDate
            if(osc[1] < osc[0] and osc[0] > 0)
                strategy.entry("Buy", strategy.long, qty=math.round((account/close)/2), limit=low, comment="tier: "+str.tostring(lastclosedtrade))

        if strategy.opentrades > 0
            if (osc[1] > osc[0] and osc[0] < 0)
                strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="close tier: 1")

            //momColor := osc[1] < osc[0] ? osc[0] >= 0 ? #00ffff : #cc00cc : osc[0] >= 0 ? #009b9b : #ff9bff

            //else if (osc[1] < osc[0] ? osc[0] >= 0 ? #00ffff : #cc00cc : osc[0] >= 0 ? #009b9b : #ff9bff)


        if Short == 1
            StopPercentage:= 2-StopPercentage
            if strategy.opentrades == 0 and afterStartDate
                if momentumLargePullback == 0
                    if(TouchedDSTLow == 1 and high > DSTEVMA)
                        strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=high, comment="tier: "+str.tostring(lastclosedtrade))
                else
                    if(TouchedDSTLow == 1 and high > upper)
                        strategy.entry("Sell", strategy.short, qty=math.round((account/close)), limit=high, comment="tier: "+str.tostring(lastclosedtrade))

            if strategy.opentrades > 0
                if (low <= lower)
                    strategy.exit("0","Sell", profit = 0.1, loss=0.1, comment="close tier: 1") //  limit=high, qty=(strategy.position_size),

                if high > strategy.opentrades.entry_price(0)*StopPercentage
                    strategy.exit("0","Sell", profit = 0.1, loss=0.1, comment="close")



    if(StrategyType == 3)
        //if we are set to going long
        if strategy.opentrades == 0 and afterStartDate
            if (high >= Week52High)
                strategy.entry("Buy", strategy.long, qty=math.round((account/close)), limit=high, comment="tier: "+str.tostring(lastclosedtrade))

        if strategy.opentrades > 0
            if low < lower or low < strategy.opentrades.entry_price(0)*StopPercentage
                strategy.exit("0","Buy", profit = 0.1, loss=0.1, comment="tier: 0 close")

